let category = {
  "1996": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Rendah",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Rendah",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Rendah",
    "Kepulauan Riau": "Rendah",
    "Jakarta Raya": "Sedang",
    "Jawa Barat": "Sedang",
    "Jawa Tengah": "Rendah",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Rendah",
    "Banten": "Rendah",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Rendah",
    "Nusa Tengggara Timur": "Rendah",
    "Kalimantan Barat": "Rendah",
    "Kalimantan Tengah": "Rendah",
    "Kalimantan Selatan": "Rendah",
    "Kalimantan Timur": "Sedang",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Sedang",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Rendah",
    "Gorontalo":"Rendah",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Sedang",
    "Maluku Utara": "Rendah",
    "Irian Jaya Barat": "Rendah",
    "Papua": "Sedang"
  },
  "1997": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Rendah",
    "Lampung": "Rendah",
    "Bangka-Belitung": "Rendah",
    "Kepulauan Riau": "Rendah",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Sedang",
    "Jawa Tengah": "Rendah",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Rendah",
    "Banten": "Rendah",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Rendah",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Rendah",
    "Kalimantan Tengah": "Rendah",
    "Kalimantan Selatan": "Rendah",
    "Kalimantan Timur": "Sedang",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Sedang",
    "Sulawesi Tengah": "Rendah",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Rendah",
    "Gorontalo":"Rendah",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Sedang",
    "Maluku Utara": "Rendah",
    "Irian Jaya Barat": "Rendah",
    "Papua": "Rendah"
  },
  "1998": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Rendah",
    "Sumatera Selatan": "Rendah",
    "Bengkulu": "Rendah",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Rendah",
    "Kepulauan Riau": "Rendah",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Sedang",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Rendah",
    "Jawa Timur": "Sedang",
    "Banten": "Rendah",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Rendah",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Rendah",
    "Kalimantan Tengah": "Sedang",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Sedang",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Sedang",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Rendah",
    "Gorontalo":"Rendah",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Rendah",
    "Maluku Utara": "Rendah",
    "Irian Jaya Barat": "Rendah",
    "Papua": "Rendah"
  },
  "1999": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Rendah",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Rendah",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Rendah",
    "Kepulauan Riau": "Rendah",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Sedang",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Rendah",
    "Jawa Timur": "Sedang",
    "Banten": "Rendah",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Rendah",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Rendah",
    "Kalimantan Tengah": "Rendah",
    "Kalimantan Selatan": "Rendah",
    "Kalimantan Timur": "Tinggi",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Sedang",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Sedang",
    "Gorontalo":"Rendah",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Sedang",
    "Maluku Utara": "Rendah",
    "Irian Jaya Barat": "Rendah",
    "Papua": "Sedang"
  },
  "2000": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Rendah",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Rendah",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Rendah",
    "Kepulauan Riau": "Rendah",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Sedang",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Rendah",
    "Jawa Timur": "Sedang",
    "Banten": "Rendah",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Rendah",
    "Kalimantan Selatan": "Rendah",
    "Kalimantan Timur": "Sedang",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Sedang",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Rendah",
    "Gorontalo":"Rendah",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Rendah",
    "Maluku Utara": "Rendah",
    "Irian Jaya Barat": "Rendah",
    "Papua": "Rendah"
  },
  "2001": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Sedang",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Sedang",
    "Kepulauan Riau": "Rendah",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Tinggi",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Sedang",
    "Banten": "Tinggi",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Sedang",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Sedang",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Sedang",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Tinggi",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Tinggi",
    "Sulawesi Tenggara": "Sedang",
    "Gorontalo":"Sedang",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Tinggi",
    "Maluku Utara": "Sedang",
    "Irian Jaya Barat": "Rendah",
    "Papua": "Sedang"
  },
  "2002": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Tinggi",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Sedang",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Sedang",
    "Kepulauan Riau": "Rendah",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Tinggi",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Sedang",
    "Banten": "Tinggi",
    "Bali": "Sedang",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Sedang",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Sedang",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Tinggi",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Tinggi",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Tinggi",
    "Sulawesi Tenggara": "Sedang",
    "Gorontalo":"Tinggi",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Sedang",
    "Maluku Utara": "Tinggi",
    "Irian Jaya Barat": "Rendah",
    "Papua": "Sedang"
  },
  "2003": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Tinggi",
    "Sumatera Barat": "Tinggi",
    "Riau": "Tinggi",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Sedang",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Sedang",
    "Kepulauan Riau": "Rendah",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Tinggi",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Sedang",
    "Banten": "Tinggi",
    "Bali": "Sedang",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Sedang",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Sedang",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Sedang",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Tinggi",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Tinggi",
    "Sulawesi Tenggara": "Tinggi",
    "Gorontalo":"Tinggi",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Tinggi",
    "Maluku Utara": "Sedang",
    "Irian Jaya Barat": "Rendah",
    "Papua": "Sedang"
  },
  "2004": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Tinggi",
    "Sumatera Barat": "Tinggi",
    "Riau": "Tinggi",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Sedang",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Sedang",
    "Kepulauan Riau": "Rendah",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Tinggi",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Sedang",
    "Banten": "Tinggi",
    "Bali": "Sedang",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Sedang",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Sedang",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Tinggi",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Tinggi",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Tinggi",
    "Sulawesi Tenggara": "Sedang",
    "Gorontalo":"Tinggi",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Tinggi",
    "Maluku Utara": "Sedang",
    "Irian Jaya Barat": "Rendah",
    "Papua": "Sedang"
  },
  "2005": {
    "Aceh": "Tinggi",
    "Sumatera Utara": "Tinggi",
    "Sumatera Barat": "Tinggi",
    "Riau": "Tinggi",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Tinggi",
    "Bengkulu": "Sedang",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Sedang",
    "Kepulauan Riau": "Rendah",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Tinggi",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Sedang",
    "Banten": "Tinggi",
    "Bali": "Sedang",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Sedang",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Sedang",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Tinggi",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Tinggi",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Tinggi",
    "Sulawesi Tenggara": "Sedang",
    "Gorontalo": "Tinggi",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Tinggi",
    "Maluku Utara": "Tinggi",
    "Irian Jaya Barat": "Rendah",
    "Papua": "Sedang"
  },
  "2006": {
    "Aceh": "Tinggi",
    "Sumatera Utara": "Tinggi",
    "Sumatera Barat": "Tinggi",
    "Riau": "Tinggi",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Tinggi",
    "Bengkulu": "Sedang",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Sedang",
    "Kepulauan Riau": "Tinggi",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Tinggi",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Sedang",
    "Banten": "Tinggi",
    "Bali": "Sedang",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Sedang",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Sedang",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Tinggi",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Tinggi",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Tinggi",
    "Sulawesi Tenggara": "Sedang",
    "Gorontalo": "Sedang",
    "Sulawesi Barat": "Sedang",
    "Maluku": "Tinggi",
    "Maluku Utara": "Sedang",
    "Irian Jaya Barat": "Tinggi",
    "Papua": "Sedang"
  },
  "2007": {
    "Aceh": "Tinggi",
    "Sumatera Utara": "Tinggi",
    "Sumatera Barat": "Tinggi",
    "Riau": "Tinggi",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Sedang",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Sedang",
    "Kepulauan Riau": "Sedang",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Tinggi",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Sedang",
    "Banten": "Tinggi",
    "Bali": "Sedang",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Sedang",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Tinggi",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Tinggi",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Tinggi",
    "Sulawesi Tenggara": "Sedang",
    "Gorontalo": "Sedang",
    "Sulawesi Barat":"Sedang",
    "Maluku": "Tinggi",
    "Maluku Utara": "Sedang",
    "Irian Jaya Barat": "Sedang",
    "Papua": "Sedang"
  },
  "2008": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Sedang",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Sedang",
    "Kepulauan Riau": "Sedang",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Tinggi",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Sedang",
    "Banten": "Tinggi",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Sedang",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Tinggi",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Tinggi",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Sedang",
    "Gorontalo":"Sedang",
    "Sulawesi Barat":"Sedang",
    "Maluku": "Tinggi",
    "Maluku Utara": "Sedang",
    "Irian Jaya Barat": "Sedang",
    "Papua": "Sedang"
  },
  "2009": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Sedang",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Sedang",
    "Kepulauan Riau": "Sedang",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Tinggi",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Sedang",
    "Banten": "Tinggi",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Sedang",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Tinggi",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Tinggi",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Sedang",
    "Gorontalo":"Sedang",
    "Sulawesi Barat":"Sedang",
    "Maluku": "Tinggi",
    "Maluku Utara": "Sedang",
    "Irian Jaya Barat": "Sedang",
    "Papua": "Sedang"
  },
  "2010": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Sedang",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Sedang",
    "Kepulauan Riau": "Sedang",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Tinggi",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Sedang",
    "Banten": "Tinggi",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Sedang",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Tinggi",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Tinggi",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Sedang",
    "Gorontalo":"Sedang",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Sedang",
    "Maluku Utara": "Sedang",
    "Irian Jaya Barat": "Sedang",
    "Papua": "Rendah"
  },
  "2011": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Rendah",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Rendah",
    "Kepulauan Riau": "Sedang",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Sedang",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Sedang",
    "Banten": "Tinggi",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Rendah",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Tinggi",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Sedang",
    "Sulawesi Tengah": "Sedang",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Sedang",
    "Gorontalo":"Sedang",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Sedang",
    "Maluku Utara": "Sedang",
    "Irian Jaya Barat": "Sedang",
    "Papua": "Sedang"
  },
  "2012": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Rendah",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Rendah",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Rendah",
    "Kepulauan Riau": "Sedang",
    "Jakarta Raya": "Tinggi",
    "Jawa Barat": "Sedang",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Rendah",
    "Jawa Timur": "Sedang",
    "Banten": "Tinggi",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Rendah",
    "Kalimantan Tengah": "Rendah",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Sedang",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Sedang",
    "Sulawesi Tengah": "Rendah",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Rendah",
    "Gorontalo":"Sedang",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Sedang",
    "Maluku Utara": "Sedang",
    "Irian Jaya Barat": "Sedang",
    "Papua": "Rendah"
  },
  "2013": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Rendah",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Rendah",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Rendah",
    "Kepulauan Riau": "Sedang",
    "Jakarta Raya": "Sedang",
    "Jawa Barat": "Sedang",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Rendah",
    "Jawa Timur": "Sedang",
    "Banten": "Sedang",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Rendah",
    "Kalimantan Tengah": "Rendah",
    "Kalimantan Selatan": "Rendah",
    "Kalimantan Timur": "Sedang",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Sedang",
    "Sulawesi Tengah": "Rendah",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Rendah",
    "Gorontalo":"Sedang",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Sedang",
    "Maluku Utara": "seddang",
    "Irian Jaya Barat": "Sedang",
    "Papua": "Rendah"
  },
  "2014": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Rendah",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Rendah",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Rendah",
    "Kepulauan Riau": "Sedang",
    "Jakarta Raya": "Sedang",
    "Jawa Barat": "Sedang",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Rendah",
    "Jawa Timur": "Sedang",
    "Banten": "Sedang",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Rendah",
    "Kalimantan Tengah": "Rendah",
    "Kalimantan Selatan": "Rendah",
    "Kalimantan Timur": "Sedang",
    "Kalimantan Utara": "Rendah",
    "Sulawesi Utara": "Sedang",
    "Sulawesi Tengah": "Rendah",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Rendah",
    "Gorontalo":"Rendah",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Sedang",
    "Maluku Utara": "Sedang",
    "Irian Jaya Barat": "Sedang",
    "Papua": "Rendah"
  },
  "2015": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Rendah",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Sedang",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Sedang",
    "Kepulauan Riau": "Sedang",
    "Jakarta Raya": "Sedang",
    "Jawa Barat": "Sedang",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Sedang",
    "Jawa Timur": "Sedang",
    "Banten": "Sedang",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Sedang",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Rendah",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Sedang",
    "Kalimantan Utara": "Sedang",
    "Sulawesi Utara": "Sedang",
    "Sulawesi Tengah": "Rendah",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Sedang",
    "Gorontalo":"Rendah",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Sedang",
    "Maluku Utara": "Sedang",
    "Irian Jaya Barat": "Sedang",
    "Papua": "Rendah"
  },
  "2016": {
    "Aceh": "Sedang",
    "Sumatera Utara": "Sedang",
    "Sumatera Barat": "Sedang",
    "Riau": "Sedang",
    "Jambi": "Sedang",
    "Sumatera Selatan": "Sedang",
    "Bengkulu": "Rendah",
    "Lampung": "Sedang",
    "Bangka-Belitung": "Sedang",
    "Kepulauan Riau": "Sedang",
    "Jakarta Raya": "Sedang",
    "Jawa Barat": "Sedang",
    "Jawa Tengah": "Sedang",
    "Yogyakarta": "Rendah",
    "Jawa Timur": "Sedang",
    "Banten": "Sedang",
    "Bali": "Rendah",
    "Nusa Tenggara Barat": "Rendah",
    "Nusa Tenggara Timur": "Rendah",
    "Kalimantan Barat": "Sedang",
    "Kalimantan Tengah": "Sedang",
    "Kalimantan Selatan": "Sedang",
    "Kalimantan Timur": "Sedang",
    "Kalimantan Utara": "Sedang",
    "Sulawesi Utara": "Sedang",
    "Sulawesi Tengah": "Rendah",
    "Sulawesi Selatan": "Sedang",
    "Sulawesi Tenggara": "Rendah",
    "Gorontalo":"Rendah",
    "Sulawesi Barat":"Rendah",
    "Maluku": "Sedang",
    "Maluku Utara": "Rendah",
    "Irian Jaya Barat": "Sedang",
    "Papua": "Rendah"
  }
};
