
let category = {
  "1996" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "rendah",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "rendah",
    "Lampung": "sedang",
    "Bangka-Belitung": "rendah",
    "Kepulauan Riau": "rendah",
    "Jakarta Raya": "sedang",
    "Jawa Barat": "sedang",
    "Jawa Tengah": "rendah",
    "Yogyakarta": "sedang",
    "Jawa Timur": "rendah",
    "Banten": "rendah",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "rendah",
    "Nusa Tengggara Timur": "rendah",
    "Kalimantan Barat": "rendah",
    "Kalimantan Tengah": "rendah",
    "Kalimantan Selatan": "rendah",
    "Kalimantan Timur": "sedang"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "sedang",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "rendah",
    "Gorontalo":"rendah",
    "Sulawesi Barat":"rendah",
    "Maluku": "sedang",
    "Maluku Utara": "rendah",
    "Irian Jaya Barat": "rendah",
    "Papua": "sedang"
  },
  "1997" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "sedang",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "rendah",
    "Lampung": "rendah",
    "Bangka-Belitung": "rendah",
    "Kepulauan Riau": "rendah",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "sedang",
    "Jawa Tengah": "rendah",
    "Yogyakarta": "sedang",
    "Jawa Timur": "rendah",
    "Banten": "rendah",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "rendah",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "rendah",
    "Kalimantan Tengah": "rendah",
    "Kalimantan Selatan": "rendah",
    "Kalimantan Timur": "sedang"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "sedang",
    "Sulawesi Tengah": "rendah",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "rendah",
    "Gorontalo":"rendah",
    "Sulawesi Barat":"rendah",
    "Maluku": "sedang",
    "Maluku Utara": "rendah",
    "Irian Jaya Barat": "rendah",
    "Papua": "rendah"
  },
  "1998" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "rendah",
    "Sumatera Selatan": "rendah",
    "Bengkulu": "rendah",
    "Lampung": "sedang",
    "Bangka-Belitung": "rendah",
    "Kepulauan Riau": "rendah",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "sedang",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "rendah",
    "Jawa Timur": "sedang",
    "Banten": "rendah",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "rendah",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "rendah",
    "Kalimantan Tengah": "sedang",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "sedang"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "sedang",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "rendah",
    "Gorontalo":"rendah",
    "Sulawesi Barat":"rendah",
    "Maluku": "rendah",
    "Maluku Utara": "rendah",
    "Irian Jaya Barat": "rendah",
    "Papua": "rendah"
  },
  "1999" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "rendah",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "rendah",
    "Lampung": "sedang",
    "Bangka-Belitung": "rendah",
    "Kepulauan Riau": "rendah",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "sedang",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "rendah",
    "Jawa Timur": "sedang",
    "Banten": "rendah",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "rendah",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "rendah",
    "Kalimantan Tengah": "rendah",
    "Kalimantan Selatan": "rendah",
    "Kalimantan Timur": "tinggi"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "sedang",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "sedang",
    "Gorontalo":"rendah",
    "Sulawesi Barat":"rendah",
    "Maluku": "sedang",
    "Maluku Utara": "rendah",
    "Irian Jaya Barat": "rendah",
    "Papua": "sedang"
  },
  "2000" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "rendah",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "rendah",
    "Lampung": "sedang",
    "Bangka-Belitung": "rendah",
    "Kepulauan Riau": "rendah",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "sedang",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "rendah",
    "Jawa Timur": "sedang",
    "Banten": "rendah",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "rendah",
    "Kalimantan Selatan": "rendah",
    "Kalimantan Timur": "sedang"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "sedang",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "rendah",
    "Gorontalo":"rendah",
    "Sulawesi Barat":"rendah",
    "Maluku": "rendah",
    "Maluku Utara": "rendah",
    "Irian Jaya Barat": "rendah",
    "Papua": "rendah"
  },
  "2001" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "sedang",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "sedang",
    "Lampung": "sedang",
    "Bangka-Belitung": "sedang",
    "Kepulauan Riau": "rendah",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "tinggi",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "sedang",
    "Jawa Timur": "sedang",
    "Banten": "tinggi",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "sedang",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "sedang",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "sedang"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "tinggi",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "tinggi",
    "Sulawesi Tenggara": "sedang",
    "Gorontalo":"sedang",
    "Sulawesi Barat":"rendah",
    "Maluku": "tinggi",
    "Maluku Utara": "sedang",
    "Irian Jaya Barat": "rendah",
    "Papua": "sedang"
  },
  "2002" = {
    "Aceh": "sedang",
    "Sumatera Utara": "tinggi",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "sedang",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "sedang",
    "Lampung": "sedang",
    "Bangka-Belitung": "sedang",
    "Kepulauan Riau": "rendah",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "tinggi",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "sedang",
    "Jawa Timur": "sedang",
    "Banten": "tinggi",
    "Bali": "sedang",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "sedang",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "sedang",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "tinggi"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "tinggi",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "tinggi",
    "Sulawesi Tenggara": "sedang",
    "Gorontalo":"tinggi",
    "Sulawesi Barat":"rendah",
    "Maluku": "sedang",
    "Maluku Utara": "tinggi",
    "Irian Jaya Barat": "rendah",
    "Papua": "sedang"
  },
  "2003" = {
    "Aceh": "sedang",
    "Sumatera Utara": "tinggi",
    "Sumatera Barat": "tinggi",
    "Riau": "tinggi",
    "Jambi": "sedang",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "sedang",
    "Lampung": "sedang",
    "Bangka-Belitung": "sedang",
    "Kepulauan Riau": "rendah",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "tinggi",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "sedang",
    "Jawa Timur": "sedang",
    "Banten": "tinggi",
    "Bali": "sedang",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "sedang",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "sedang",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "sedang"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "tinggi",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "tinggi",
    "Sulawesi Tenggara": "tinggi",
    "Gorontalo":"tinggi",
    "Sulawesi Barat":"rendah",
    "Maluku": "tinggi",
    "Maluku Utara": "sedang",
    "Irian Jaya Barat": "rendah",
    "Papua": "sedang"
  },
  "2004" = {
    "Aceh": "sedang",
    "Sumatera Utara": "tinggi",
    "Sumatera Barat": "tinggi",
    "Riau": "tinggi",
    "Jambi": "sedang",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "sedang",
    "Lampung": "sedang",
    "Bangka-Belitung": "sedang",
    "Kepulauan Riau": "rendah",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "tinggi",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "sedang",
    "Jawa Timur": "sedang",
    "Banten": "tinggi",
    "Bali": "sedang",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "sedang",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "sedang",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "tinggi"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "tinggi",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "tinggi",
    "Sulawesi Tenggara": "sedang",
    "Gorontalo":"tinggi",
    "Sulawesi Barat":"rendah",
    "Maluku": "tinggi",
    "Maluku Utara": "sedang",
    "Irian Jaya Barat": "rendah",
    "Papua": "sedang"
  },
  "2005" = {
    "Aceh": "tinggi",
    "Sumatera Utara": "tinggi",
    "Sumatera Barat": "tinggi",
    "Riau": "tinggi",
    "Jambi": "sedang",
    "Sumatera Selatan": "tinggi",
    "Bengkulu": "sedang",
    "Lampung": "sedang",
    "Bangka-Belitung": "sedang",
    "Kepulauan Riau": "rendah",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "tinggi",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "sedang",
    "Jawa Timur": "sedang",
    "Banten": "tinggi",
    "Bali": "sedang",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "sedang",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "sedang",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "tinggi"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "tinggi",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "tinggi",
    "Sulawesi Tenggara": "sedang",
    "Gorontalo": "tinggi",
    "Sulawesi Barat":"rendah",
    "Maluku": "tinggi",
    "Maluku Utara": "tinggi",
    "Irian Jaya Barat": "rendah",
    "Papua": "sedang"
  },
  "2006" = {
    "Aceh": "tinggi",
    "Sumatera Utara": "tinggi",
    "Sumatera Barat": "tinggi",
    "Riau": "tinggi",
    "Jambi": "sedang",
    "Sumatera Selatan": "tinggi",
    "Bengkulu": "sedang",
    "Lampung": "sedang",
    "Bangka-Belitung": "sedang",
    "Kepulauan Riau": "tinggi",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "tinggi",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "sedang",
    "Jawa Timur": "sedang",
    "Banten": "tinggi",
    "Bali": "sedang",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "sedang",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "sedang",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "tinggi"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "tinggi",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "tinggi",
    "Sulawesi Tenggara": "sedang",
    "Gorontalo": "sedang",
    "Sulawesi Barat": "sedang",
    "Maluku": "tinggi",
    "Maluku Utara": "sedang",
    "Irian Jaya Barat": "tinggi",
    "Papua": "sedang"
  },
  "2007" = {
    "Aceh": "tinggi",
    "Sumatera Utara": "tinggi",
    "Sumatera Barat": "tinggi",
    "Riau": "tinggi",
    "Jambi": "sedang",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "sedang",
    "Lampung": "sedang",
    "Bangka-Belitung": "sedang",
    "Kepulauan Riau": "sedang",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "tinggi",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "sedang",
    "Jawa Timur": "sedang",
    "Banten": "tinggi",
    "Bali": "sedang",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "sedang",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "tinggi"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "tinggi",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "tinggi",
    "Sulawesi Tenggara": "sedang",
    "Gorontalo": "sedang",
    "Sulawesi Barat":"sedang",
    "Maluku": "tinggi",
    "Maluku Utara": "sedang",
    "Irian Jaya Barat": "sedang",
    "Papua": "sedang"
  },
  "2008" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "sedang",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "sedang",
    "Lampung": "sedang",
    "Bangka-Belitung": "sedang",
    "Kepulauan Riau": "sedang",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "tinggi",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "sedang",
    "Jawa Timur": "sedang",
    "Banten": "tinggi",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "sedang",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "tinggi"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "tinggi",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "sedang",
    "Gorontalo":"sedang",
    "Sulawesi Barat":"sedang",
    "Maluku": "tinggi",
    "Maluku Utara": "sedang",
    "Irian Jaya Barat": "sedang",
    "Papua": "sedang"
  },
  "2009" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "sedang",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "sedang",
    "Lampung": "sedang",
    "Bangka-Belitung": "sedang",
    "Kepulauan Riau": "sedang",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "tinggi",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "sedang",
    "Jawa Timur": "sedang",
    "Banten": "tinggi",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "sedang",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "tinggi"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "tinggi",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "sedang",
    "Gorontalo":"sedang",
    "Sulawesi Barat":"sedang",
    "Maluku": "tinggi",
    "Maluku Utara": "sedang",
    "Irian Jaya Barat": "sedang",
    "Papua": "sedang"
  },
  "2010" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "sedang",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "sedang",
    "Lampung": "sedang",
    "Bangka-Belitung": "sedang",
    "Kepulauan Riau": "sedang",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "tinggi",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "sedang",
    "Jawa Timur": "sedang",
    "Banten": "tinggi",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "sedang",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "tinggi"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "tinggi",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "sedang",
    "Gorontalo":"sedang",
    "Sulawesi Barat":"rendah",
    "Maluku": "sedang",
    "Maluku Utara": "sedang",
    "Irian Jaya Barat": "sedang",
    "Papua": "rendah"
  },
  "2011" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "sedang",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "rendah",
    "Lampung": "sedang",
    "Bangka-Belitung": "rendah",
    "Kepulauan Riau": "sedang",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "sedang",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "sedang",
    "Jawa Timur": "sedang",
    "Banten": "tinggi",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "rendah",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "tinggi"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "sedang",
    "Sulawesi Tengah": "sedang",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "sedang",
    "Gorontalo":"sedang",
    "Sulawesi Barat":"rendah",
    "Maluku": "sedang",
    "Maluku Utara": "sedang",
    "Irian Jaya Barat": "sedang",
    "Papua": "sedang"
  },
  "2012" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "rendah",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "rendah",
    "Lampung": "sedang",
    "Bangka-Belitung": "rendah",
    "Kepulauan Riau": "sedang",
    "Jakarta Raya": "tinggi",
    "Jawa Barat": "sedang",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "rendah",
    "Jawa Timur": "sedang",
    "Banten": "tinggi",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "rendah",
    "Kalimantan Tengah": "rendah",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "sedang"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "sedang",
    "Sulawesi Tengah": "rendah",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "rendah",
    "Gorontalo":"sedang",
    "Sulawesi Barat":"rendah",
    "Maluku": "sedang",
    "Maluku Utara": "sedang",
    "Irian Jaya Barat": "sedang",
    "Papua": "rendah"
  },
  "2013" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "rendah",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "rendah",
    "Lampung": "sedang",
    "Bangka-Belitung": "rendah",
    "Kepulauan Riau": "sedang",
    "Jakarta Raya": "sedang",
    "Jawa Barat": "sedang",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "rendah",
    "Jawa Timur": "sedang",
    "Banten": "sedang",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "rendah",
    "Kalimantan Tengah": "rendah",
    "Kalimantan Selatan": "rendah",
    "Kalimantan Timur": "sedang"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "sedang",
    "Sulawesi Tengah": "rendah",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "rendah",
    "Gorontalo":"sedang",
    "Sulawesi Barat":"rendah",
    "Maluku": "sedang",
    "Maluku Utara": "seddang",
    "Irian Jaya Barat": "sedang",
    "Papua": "rendah"
  },
  "2014" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "rendah",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "rendah",
    "Lampung": "sedang",
    "Bangka-Belitung": "rendah",
    "Kepulauan Riau": "sedang",
    "Jakarta Raya": "sedang",
    "Jawa Barat": "sedang",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "rendah",
    "Jawa Timur": "sedang",
    "Banten": "sedang",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "rendah",
    "Kalimantan Tengah": "rendah",
    "Kalimantan Selatan": "rendah",
    "Kalimantan Timur": "sedang"
    "Kalimantan Utara": "rendah",
    "Sulawesi Utara": "sedang",
    "Sulawesi Tengah": "rendah",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "rendah",
    "Gorontalo":"rendah",
    "Sulawesi Barat":"rendah",
    "Maluku": "sedang",
    "Maluku Utara": "sedang",
    "Irian Jaya Barat": "sedang",
    "Papua": "rendah"
  },
  "2015" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "rendah",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "sedang",
    "Lampung": "sedang",
    "Bangka-Belitung": "sedang",
    "Kepulauan Riau": "sedang",
    "Jakarta Raya": "sedang",
    "Jawa Barat": "sedang",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "sedang",
    "Jawa Timur": "sedang",
    "Banten": "sedang",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "sedang",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "rendah",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "sedang"
    "Kalimantan Utara": "sedang",
    "Sulawesi Utara": "sedang",
    "Sulawesi Tengah": "rendah",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "sedang",
    "Gorontalo":"rendah",
    "Sulawesi Barat":"rendah",
    "Maluku": "sedang",
    "Maluku Utara": "sedang",
    "Irian Jaya Barat": "sedang",
    "Papua": "rendah"
  },
  "2016" = {
    "Aceh": "sedang",
    "Sumatera Utara": "sedang",
    "Sumatera Barat": "sedang",
    "Riau": "sedang",
    "Jambi": "sedang",
    "Sumatera Selatan": "sedang",
    "Bengkulu": "rendah",
    "Lampung": "sedang",
    "Bangka-Belitung": "sedang",
    "Kepulauan Riau": "sedang",
    "Jakarta Raya": "sedang",
    "Jawa Barat": "sedang",
    "Jawa Tengah": "sedang",
    "Yogyakarta": "rendah",
    "Jawa Timur": "sedang",
    "Banten": "sedang",
    "Bali": "rendah",
    "Nusa Tenggara Barat": "rendah",
    "Nusa Tenggara Timur": "rendah",
    "Kalimantan Barat": "sedang",
    "Kalimantan Tengah": "sedang",
    "Kalimantan Selatan": "sedang",
    "Kalimantan Timur": "sedang"
    "Kalimantan Utara": "sedang",
    "Sulawesi Utara": "sedang",
    "Sulawesi Tengah": "rendah",
    "Sulawesi Selatan": "sedang",
    "Sulawesi Tenggara": "rendah",
    "Gorontalo":"rendah",
    "Sulawesi Barat":"rendah",
    "Maluku": "sedang",
    "Maluku Utara": "rendah",
    "Irian Jaya Barat": "sedang",
    "Papua": "rendah"
  }
}
