let category = {
    "1996" : {
        "Aceh": "Sedang",
        "Sumatera Utara": "Sedang",
        "Sumatera Barat": "Sedang",
        "Riau": "Sedang",
        "Jambi": "Rendah",
        "Sumatera Selatan": "Sedang",
        "Bengkulu": "Rendah",
        "Lampung": "Sedang",
        "Bangka-Belitung": "Tinggi",
        "Kepulauan Riau": "Tinggi",
        "Jakarta Raya": "Sedang",
        "Jawa Barat": "Sedang",
        "Jawa Tengah": "Tinggi",
        "Yogyakarta": "Sedang",
        "Jawa Timur": "Tinggi",
        "Banten": "Rendah",
        "Bali": "Rendah",
        "Nusa Tenggara Barat": "Rendah",
        "Nusa Tenggara Timur": "Rendah",
        "Kalimantan Barat": "Rendah",
        "Kalimantan Tengah": "Rendah",
        "Kalimantan Selatan": "Rendah",
        "Kalimantan Timur": "Sedang",
        "Kalimantan Utara": "Rendah",
        "Sulawesi Utara": "Sedang",
        "Sulawesi Tengah": "Sedang",
        "Sulawesi Selatan": "Sedang",
        "Sulawesi Tenggara": "Rendah",
        "Gorontalo": "Rendah",
        "Sulawesi Barat": "Rendah",
        "Maluku": "Sedang",
        "Maluku Utara": "Rendah",
        "Irian Jaya Barat": "Sedang",
        "Papua": "Sedang"
    },

    "1997" : {
        "Aceh": "Tinggi",
        "Sumatera Utara": "Tinggi",
        "Sumatera Barat": "Tinggi",
        "Riau": "Tinggi",
        "Jambi": "Rendah",
        "Sumatera Selatan": "Tinggi",
        "Bengkulu": "Rendah",
        "Lampung": "Tinggi",
        "Bangka-Belitung": "Tinggi",
        "Kepulauan Riau": "Tinggi",
        "Jakarta Raya": "Tinggi",
        "Jawa Barat": "Tinggi",
        "Jawa Tengah": "Tinggi",
        "Yogyakarta": "Tinggi",
        "Jawa Timur": "Tinggi",
        "Banten": "Rendah",
        "Bali": "Rendah",
        "Nusa Tenggara Barat": "Rendah",
        "Nusa Tenggara Timur": "Rendah",
        "Kalimantan Barat": "Rendah",
        "Kalimantan Tengah": "Rendah",
        "Kalimantan Selatan": "Rendah",
        "Kalimantan Timur": "Tinggi",
        "Kalimantan Utara": "Rendah",
        "Sulawesi Utara": "Tinggi",
        "Sulawesi Tengah": "Tinggi",
        "Sulawesi Selatan": "Tinggi",
        "Sulawesi Tenggara": "Rendah",
        "Gorontalo": "Rendah",
        "Sulawesi Barat": "Rendah",
        "Maluku": "Tinggi",
        "Maluku Utara": "Rendah",
        "Irian Jaya Barat": "Sedang",
        "Papua": "Sedang"
    }
};
